sonar.projectKey=YOUR_PROJECT_KEY
sonar.organization=YOUR_ORGANIZATION_KEY

sonar.sources=.
sonar.exclusions=test_app.py,k8s/**,Dockerfile,requirements.txt,README.md
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
